server:
  port: 8050 # 指定实例端口号
eureka:
  instance:
    prefer-ip-address: true # 是否显示主机的IP
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # status列的显示名称
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 指定Eureka服务端地址
spring:
  application:
    name: microservice-gateway-zuul  # 指定应用名称

zuul:
  routes:
    order-serviceId: # zuul 的 唯一标识
      path: /order-url/**
      service-id: microservice-eureka-order